// Shared product data used across the app
import { Product } from '@/components/ui/ProductCard';

export const PRODUCTS: Product[] = [
    {
        id: '1',
        name: 'Professional 20V Cordless Drill Kit',
        brand: 'Bosch',
        category: 'Power Tools',
        price: 8499,
        originalPrice: 12000,
        discount: 29,
        rating: 4.8,
        reviews: 238,
        image: '🔧',
        badge: 'Hot',
        inStock: true,
        stockLevel: 'in-stock',
        features: ['20V max lithium battery', '0-1800 RPM variable speed', 'LED work light included'],
        isNew: false,
        flashSale: true,
    },
    {
        id: '2',
        name: 'LED Smart Bulb E27 9W (Pack of 6)',
        brand: 'Philips',
        category: 'Lighting',
        price: 1899,
        originalPrice: 2400,
        discount: 21,
        rating: 4.6,
        reviews: 512,
        image: '💡',
        inStock: true,
        stockLevel: 'in-stock',
        isNew: true,
        flashSale: false,
    },
    {
        id: '3',
        name: 'Heavy Duty Extension Cord 10m',
        brand: 'Havells',
        category: 'Electrical',
        price: 1299,
        rating: 4.5,
        reviews: 189,
        image: '🔌',
        inStock: true,
        stockLevel: 'in-stock',
        flashSale: false,
    },
    {
        id: '4',
        name: 'Angle Grinder 115mm 750W',
        brand: 'Makita',
        category: 'Power Tools',
        price: 6499,
        originalPrice: 8200,
        discount: 21,
        rating: 4.7,
        reviews: 341,
        image: '⚙️',
        inStock: true,
        stockLevel: 'low-stock',
        flashSale: true,
    },
    {
        id: '5',
        name: 'PVC Pressure Pipe 25mm × 6m',
        brand: 'Amass',
        category: 'Plumbing',
        price: 850,
        rating: 4.3,
        reviews: 92,
        image: '🔩',
        inStock: true,
        stockLevel: 'in-stock',
        flashSale: false,
    },
    {
        id: '6',
        name: 'Safety Hard Hat Yellow',
        brand: 'MSA',
        category: 'Safety Equipment',
        price: 599,
        rating: 4.4,
        reviews: 156,
        image: '⛑️',
        inStock: true,
        stockLevel: 'in-stock',
        isNew: true,
        flashSale: false,
    },
    {
        id: '7',
        name: 'Interior Wall Paint 4L Brilliant White',
        brand: 'Crown Paints',
        category: 'Paint',
        price: 1750,
        originalPrice: 2100,
        discount: 17,
        rating: 4.5,
        reviews: 208,
        image: '🎨',
        inStock: true,
        stockLevel: 'in-stock',
        flashSale: false,
    },
    {
        id: '8',
        name: 'Stainless Steel Hand Trowel',
        brand: 'Stanley',
        category: 'Hand Tools',
        price: 450,
        rating: 4.2,
        reviews: 74,
        image: '🔨',
        inStock: false,
        stockLevel: 'out-of-stock',
        flashSale: false,
    },
    {
        id: '9',
        name: 'Circular Saw 185mm 1400W',
        brand: 'DeWalt',
        category: 'Power Tools',
        price: 11999,
        originalPrice: 15000,
        discount: 20,
        rating: 4.9,
        reviews: 421,
        image: '🪚',
        inStock: true,
        stockLevel: 'in-stock',
        isNew: false,
        flashSale: true,
    },
    {
        id: '10',
        name: 'Garden Water Hose 30m',
        brand: 'Fitt',
        category: 'Garden',
        price: 2200,
        rating: 4.1,
        reviews: 63,
        image: '🌿',
        inStock: true,
        stockLevel: 'low-stock',
        flashSale: false,
    },
    {
        id: '11',
        name: 'Electrical Switchboard 10-Way',
        brand: 'ABB',
        category: 'Electrical',
        price: 4500,
        originalPrice: 5500,
        discount: 18,
        rating: 4.7,
        reviews: 130,
        image: '🔋',
        inStock: true,
        stockLevel: 'in-stock',
        isNew: true,
        flashSale: false,
    },
    {
        id: '12',
        name: 'Measuring Tape 5m Steel',
        brand: 'Stanley',
        category: 'Hand Tools',
        price: 380,
        rating: 4.6,
        reviews: 298,
        image: '📏',
        inStock: true,
        stockLevel: 'in-stock',
        flashSale: false,
    },
];
